name: Setup Flutter

description: Setup Flutter environment on GitHub Actions runner.

inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'GitHub Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    # fvm のバージョン で Flutter SDK を設定する
    - name: Setup Flutter SDK
      uses: kuhnroyal/flutter-fvm-config-action/setup@v3
